name: irrm-codec
channels:
  - pytorch
  - conda-forge
dependencies:
  - python=3.11
  - numpy
  - pandas
  - pyarrow
  - fastparquet
  - matplotlib
  - seaborn
  - scikit-learn
  - jupyterlab
  - notebook
  - ipykernel
  - ipywidgets
  - pytorch
